const entertainment_json = [
  {
    "breaking": false, 
    "category": "Star Style", 
    "fb_comments": 4, 
    "fb_engagements": 15, 
    "fb_reactions": 8, 
    "fb_shares": 3, 
    "headline": "Star Style: Lion Mums star Nurul Aini combines effortless chic with added comfort", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/large-portrait/public/articles/2019/06/04/NP_20190604_LGSTYLE04XCAP_4886383.jpg?itok=gUS6tp1s", 
    "lead": "Now that Nurul Aini is eight months pregnant with her third child, fashion has taken a back seat.", 
    "published_date": "04 June 2019", 
    "standfirst": "Lion Mums star Nurul Aini manages to look elegant even when eight months pregnant with outfits that are both trendy and comfortable", 
    "tag": "FASHION", 
    "url": "https://www.tnp.sg/entertainment/star-style/star-style-lion-mums-nurul-aini-combines-effortless-chic-added-comfort"
  }, 
  {
    "breaking": false, 
    "category": "School of Frock", 
    "fb_comments": 0, 
    "fb_engagements": 0, 
    "fb_reactions": 0, 
    "fb_shares": 0, 
    "headline": "School of Frock: It ain't broke, so Claudia Schiffer doesn't need to fix it", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/image_embed/public/articles/2019/06/04/NP_20190604_JMFASH04APJ8_4886291.jpg?itok=AyYcslVc", 
    "lead": "Premiere of Rocketman in New York City", 
    "published_date": "04 June 2019", 
    "standfirst": "Thank goodness for Claudia Schiffer, the oasis in the post-Cannes fashion desert", 
    "tag": "FASHION", 
    "url": "https://www.tnp.sg/entertainment/school-frock/school-frock-it-aint-broke-so-claudia-schiffer-doesnt-need-fix-it"
  }, 
  {
    "breaking": false, 
    "category": "Movies", 
    "fb_comments": 0, 
    "fb_engagements": 0, 
    "fb_reactions": 0, 
    "fb_shares": 0, 
    "headline": "Godzilla: King Of The Monsters tame at US box office", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/06/04/NP_20190604_SHOW04_4886319.jpg?itok=JPyb7a1m", 
    "lead": "Godzilla: King Of The Monsters may be king of the US box office, but it only managed a meek roar.", 
    "published_date": "04 June 2019", 
    "standfirst": "", 
    "tag": "MOVIES", 
    "url": "https://www.tnp.sg/entertainment/movies/godzilla-king-monsters-tame-us-box-office"
  }, 
  {
    "breaking": false, 
    "category": "Music", 
    "fb_comments": 0, 
    "fb_engagements": 0, 
    "fb_reactions": 0, 
    "fb_shares": 0, 
    "headline": "Guns N\u2019 Roses sues brewery over beer name", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/05/13/NP_20190513_SHOW13_4835496.jpg?itok=QOiKURce", 
    "lead": "LOS ANGELES The US rock band Guns N' Roses (GNR) is suing a Colorado brewery for naming one of its beers Guns 'N' Rose, saying the alleged trademark infringement caused the hard rockers \"irreparable damage\".", 
    "published_date": "13 May 2019", 
    "standfirst": "", 
    "tag": "FOOD & DRINK", 
    "url": "https://www.tnp.sg/entertainment/music/guns-n-roses-sues-brewery-over-beer-name"
  }, 
  {
    "breaking": false, 
    "category": "TV", 
    "fb_comments": 0, 
    "fb_engagements": 0, 
    "fb_reactions": 0, 
    "fb_shares": 0, 
    "headline": "Kim Kardashian and Kanye West welcome new baby", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/05/13/NP_20190513_SHOW13BY2B_4835497.jpg?itok=hnZ4VvxD", 
    "lead": "NEW YORK US reality TV star Kim Kardashian West said on Friday that she and her husband, rapper Kanye West, have welcomed their fourth child, a boy born via surrogate.", 
    "published_date": "13 May 2019", 
    "standfirst": "", 
    "tag": "CELEBRITIES", 
    "url": "https://www.tnp.sg/entertainment/tv/kim-kardashian-and-kanye-west-welcome-new-baby"
  }, 
  {
    "breaking": false, 
    "category": "Music", 
    "fb_comments": 0, 
    "fb_engagements": 1, 
    "fb_reactions": 0, 
    "fb_shares": 0, 
    "headline": "Kim Lee: Female DJs \u2018have a lot to prove\u2019", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/04/29/NP_20190429_JLKIM29TB2U_4803872.jpg?itok=9HkaezeW", 
    "lead": "From hot club DJs like Jade Rasif from Singapore to Malaysia's Leng Yein, there seems to be a type of look that a woman needs to adopt to make it big on the nightlife scene.", 
    "published_date": "29 April 2019", 
    "standfirst": "'Asian Kim Kardashian' describes challenges of being a hot woman in the industry", 
    "tag": "CELEBRITIES", 
    "url": "https://www.tnp.sg/entertainment/music/kim-lee-female-djs-have-lot-prove"
  }
];