const sgfocus_json = [
  {
    "breaking": true, 
    "category": "Singapore", 
    "fb_comments": 21, 
    "fb_engagements": 164, 
    "fb_reactions": 94, 
    "fb_shares": 49, 
    "headline": "Passers-by scramble to help woman trapped in car", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/06/04/NP_20190604_SNCRASH048RXK_4887023.jpg?itok=qAxFqrLZ", 
    "lead": "A group of six people scrambled to free a woman locked in her car after it mounted a kerb and crashed into tables and chairs at an Indian-Muslim eatery.", 
    "published_date": "04 June 2019", 
    "standfirst": "She crashes into tables at Geylang eatery, after apparently having seizure", 
    "tag": "ACCIDENTS FIRE FLOOD", 
    "url": "https://www.tnp.sg/news/singapore/passers-scramble-help-woman-trapped-car"
  }, 
  {
    "breaking": true, 
    "category": "Singapore", 
    "fb_comments": 88, 
    "fb_engagements": 288, 
    "fb_reactions": 147, 
    "fb_shares": 53, 
    "headline": "Sundown Marathon apologises for late flag-off, lack of water", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/06/04/NP_20190604_SDRUN04L6MB_4887048.jpg?itok=INrz4nrO", 
    "lead": "Runners at this year's Osim Sundown Marathon, organised by Infinitus Productions, were left frustrated when they could not get water at certain designated points of the run.", 
    "published_date": "04 June 2019", 
    "standfirst": "", 
    "tag": "COMMUNITY ISSUES", 
    "url": "https://www.tnp.sg/news/singapore/sundown-marathon-apologises-late-flag-lack-water"
  }, 
  {
    "breaking": true, 
    "category": "Singapore", 
    "fb_comments": 270, 
    "fb_engagements": 654, 
    "fb_reactions": 242, 
    "fb_shares": 142, 
    "headline": "Fans upset as Ultra Singapore music festival shifts indoors ", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/06/04/NP_20190604_YFULTRA04_4887202.jpg?itok=43xATKjZ", 
    "lead": "Revellers hoping to spend this weekend at outdoor electronic dance music (EDM) festival Ultra Singapore are up in arms after a last-minute change in venue.", 
    "published_date": "04 June 2019", 
    "standfirst": "Move comes at last minute. 'I feel this is unfair' says regular festival-goer", 
    "tag": "CONSUMER ISSUES", 
    "url": "https://www.tnp.sg/news/singapore/fans-upset-music-festival-ultra-singapore-shifts-indoors"
  }, 
  {
    "breaking": true, 
    "category": "Singapore", 
    "fb_comments": 43, 
    "fb_engagements": 241, 
    "fb_reactions": 79, 
    "fb_shares": 119, 
    "headline": "Woman nearly dies from taking slimming drug; HSA issues advisory on products containing banned substance", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/06/04/np_20190604_dbhsa032ak2_4887eee000.jpg?itok=xtZxkDcS", 
    "lead": "A woman in her 50s needed to be resuscitated after she lost consciousness from consuming a slimming product for three months.", 
    "published_date": "04 June 2019", 
    "standfirst": "HSA warns of three illegal slimming products sold online that can cause heart failure", 
    "tag": "CONSUMER ISSUES", 
    "url": "https://www.tnp.sg/news/singapore/woman-nearly-dies-taking-slimming-drug-hsa-issues-advisory-products-containing-banned"
  }, 
  {
    "breaking": true, 
    "category": "Singapore", 
    "fb_comments": 6, 
    "fb_engagements": 64, 
    "fb_reactions": 37, 
    "fb_shares": 21, 
    "headline": "Heavy rain causes flooding at People's Park Complex ", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/06/04/np_20190604_flood04ctjh_4887097.jpg?itok=GIZ2de7f", 
    "lead": "There was flooding on three storeys of People's Park Complex in Chinatown during a heavy afternoon downpour yesterday.", 
    "published_date": "04 June 2019", 
    "standfirst": "Water from car park overflows into shop areas on first 3 storeys", 
    "tag": "ACCIDENTS FIRE FLOOD", 
    "url": "https://www.tnp.sg/news/singapore/heavy-rain-causes-flooding-peoples-park-complex"
  }, 
  {
    "breaking": false, 
    "category": "Singapore", 
    "fb_comments": 8, 
    "fb_engagements": 46, 
    "fb_reactions": 26, 
    "fb_shares": 12, 
    "headline": "Elderly man, 70, hurt as hawker centre seat comes apart", 
    "img_src": "https://www.tnp.sg/sites/default/files/styles/rl380/public/articles/2019/06/04/NP_20190604_NHHAWKER_4887049.jpg?itok=DHpvENXM", 
    "lead": "A 70-year-old man fell and hurt his head after the stool he was sitting on at Teck Ghee Square hawker centre came apart.", 
    "published_date": "04 June 2019", 
    "standfirst": "", 
    "tag": "COMMUNITY ISSUES", 
    "url": "https://www.tnp.sg/news/singapore/elderly-man-70-hurt-hawker-centre-seat-comes-apart"
  }
];